# docker/docker-compose.yaml
services:
  # The Go Application Service
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: crapp-go
    ports:
      - "8080:8080"
    volumes:
      # Mount the local server directory into the container for live reloading.
      - ./server:/app/server
      - ./config:/app/config
    environment:
      # Environment variables for connecting to the database.
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=crappdb
    depends_on:
      - db # Ensures the 'db' service starts before the 'server' service.
    # The command to run for development with live-reloading.
    command: air

  # The PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crappdb
    ports:
      - "5432:5432" # Expose the database port to the host machine for easy access.
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist database data.

volumes:
  postgres-data: # Defines the named volume for data persistence.