server:
  port: "5050"
  # session_secret: "supersecret"          Set in .env file

database:
  host: "db"
  # port: "5432"          Set in .env file
  # user: "user"          Set in .env file
  # password: "password"  Set in .env file
  # dbname: "db"          Set in .env file


