package utils

// TimeZone represents a single timezone for the dropdown.
type TimeZone struct {
	Value string
	Label string
}

// GetTimeZones returns a list of common IANA timezone identifiers.
// This list is not exhaustive but covers most major regions.
func GetTimeZones() []TimeZone {
	return []TimeZone{
		{Value: "Etc/GMT+12", Label: "(GMT-12:00) International Date Line West"},
		{Value: "Pacific/Midway", Label: "(GMT-11:00) Midway Island, Samoa"},
		{Value: "Pacific/Honolulu", Label: "(GMT-10:00) Hawaii"},
		{Value: "US/Alaska", Label: "(GMT-09:00) Alaska"},
		{Value: "America/Los_Angeles", Label: "(GMT-08:00) Pacific Time (US & Canada)"},
		{Value: "America/Tijuana", Label: "(GMT-08:00) Tijuana, Baja California"},
		{Value: "US/Arizona", Label: "(GMT-07:00) Arizona"},
		{Value: "America/Chihuahua", Label: "(GMT-07:00) Chihuahua, La Paz, Mazatlan"},
		{Value: "US/Mountain", Label: "(GMT-07:00) Mountain Time (US & Canada)"},
		{Value: "America/Managua", Label: "(GMT-06:00) Central America"},
		{Value: "US/Central", Label: "(GMT-06:00) Central Time (US & Canada)"},
		{Value: "America/Mexico_City", Label: "(GMT-06:00) Guadalajara, Mexico City, Monterrey"},
		{Value: "Canada/Saskatchewan", Label: "(GMT-06:00) Saskatchewan"},
		{Value: "America/Bogota", Label: "(GMT-05:00) Bogota, Lima, Quito, Rio Branco"},
		{Value: "US/Eastern", Label: "(GMT-05:00) Eastern Time (US & Canada)"},
		{Value: "US/East-Indiana", Label: "(GMT-05:00) Indiana (East)"},
		{Value: "Canada/Atlantic", Label: "(GMT-04:00) Atlantic Time (Canada)"},
		{Value: "America/Caracas", Label: "(GMT-04:00) Caracas, La Paz"},
		{Value: "America/Manaus", Label: "(GMT-04:00) Manaus"},
		{Value: "America/Santiago", Label: "(GMT-04:00) Santiago"},
		{Value: "Canada/Newfoundland", Label: "(GMT-03:30) Newfoundland"},
		{Value: "America/Sao_Paulo", Label: "(GMT-03:00) Brasilia"},
		{Value: "America/Argentina/Buenos_Aires", Label: "(GMT-03:00) Buenos Aires, Georgetown"},
		{Value: "America/Godthab", Label: "(GMT-03:00) Greenland"},
		{Value: "America/Montevideo", Label: "(GMT-03:00) Montevideo"},
		{Value: "America/Noronha", Label: "(GMT-02:00) Mid-Atlantic"},
		{Value: "Atlantic/Cape_Verde", Label: "(GMT-01:00) Cape Verde Is."},
		{Value: "Atlantic/Azores", Label: "(GMT-01:00) Azores"},
		{Value: "Africa/Casablanca", Label: "(GMT+00:00) Casablanca, Monrovia, Reykjavik"},
		{Value: "Etc/Greenwich", Label: "(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London"},
		{Value: "Europe/Amsterdam", Label: "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
		{Value: "Europe/Belgrade", Label: "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
		{Value: "Europe/Brussels", Label: "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris"},
		{Value: "Europe/Sarajevo", Label: "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb"},
		{Value: "Africa/Lagos", Label: "(GMT+01:00) West Central Africa"},
		{Value: "Asia/Amman", Label: "(GMT+02:00) Amman"},
		{Value: "Europe/Athens", Label: "(GMT+02:00) Athens, Bucharest, Istanbul"},
		{Value: "Asia/Beirut", Label: "(GMT+02:00) Beirut"},
		{Value: "Africa/Cairo", Label: "(GMT+02:00) Cairo"},
		{Value: "Africa/Harare", Label: "(GMT+02:00) Harare, Pretoria"},
		{Value: "Europe/Helsinki", Label: "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
		{Value: "Asia/Jerusalem", Label: "(GMT+02:00) Jerusalem"},
		{Value: "Europe/Minsk", Label: "(GMT+03:00) Minsk"},
		{Value: "Asia/Baghdad", Label: "(GMT+03:00) Baghdad"},
		{Value: "Asia/Kuwait", Label: "(GMT+03:00) Kuwait, Riyadh"},
		{Value: "Europe/Moscow", Label: "(GMT+03:00) Moscow, St. Petersburg, Volgograd"},
		{Value: "Africa/Nairobi", Label: "(GMT+03:00) Nairobi"},
		{Value: "Asia/Tbilisi", Label: "(GMT+03:00) Tbilisi"},
		{Value: "Asia/Tehran", Label: "(GMT+03:30) Tehran"},
		{Value: "Asia/Muscat", Label: "(GMT+04:00) Abu Dhabi, Muscat"},
		{Value: "Asia/Baku", Label: "(GMT+04:00) Baku"},
		{Value: "Asia/Yerevan", Label: "(GMT+04:00) Yerevan"},
		{Value: "Asia/Kabul", Label: "(GMT+04:30) Kabul"},
		{Value: "Asia/Yekaterinburg", Label: "(GMT+05:00) Yekaterinburg"},
		{Value: "Asia/Karachi", Label: "(GMT+05:00) Islamabad, Karachi, Tashkent"},
		{Value: "Asia/Calcutta", Label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi"},
		{Value: "Asia/Katmandu", Label: "(GMT+05:45) Kathmandu"},
		{Value: "Asia/Almaty", Label: "(GMT+06:00) Almaty, Novosibirsk"},
		{Value: "Asia/Dhaka", Label: "(GMT+06:00) Astana, Dhaka"},
		{Value: "Asia/Rangoon", Label: "(GMT+06:30) Yangon (Rangoon)"},
		{Value: "Asia/Bangkok", Label: "(GMT+07:00) Bangkok, Hanoi, Jakarta"},
		{Value: "Asia/Krasnoyarsk", Label: "(GMT+07:00) Krasnoyarsk"},
		{Value: "Asia/Hong_Kong", Label: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi"},
		{Value: "Asia/Kuala_Lumpur", Label: "(GMT+08:00) Kuala Lumpur, Singapore"},
		{Value: "Asia/Irkutsk", Label: "(GMT+08:00) Irkutsk, Ulaan Bataar"},
		{Value: "Australia/Perth", Label: "(GMT+08:00) Perth"},
		{Value: "Asia/Taipei", Label: "(GMT+08:00) Taipei"},
		{Value: "Asia/Tokyo", Label: "(GMT+09:00) Osaka, Sapporo, Tokyo"},
		{Value: "Asia/Seoul", Label: "(GMT+09:00) Seoul"},
		{Value: "Asia/Yakutsk", Label: "(GMT+09:00) Yakutsk"},
		{Value: "Australia/Adelaide", Label: "(GMT+09:30) Adelaide"},
		{Value: "Australia/Darwin", Label: "(GMT+09:30) Darwin"},
		{Value: "Australia/Brisbane", Label: "(GMT+10:00) Brisbane"},
		{Value: "Australia/Canberra", Label: "(GMT+10:00) Canberra, Melbourne, Sydney"},
		{Value: "Australia/Hobart", Label: "(GMT+10:00) Hobart"},
		{Value: "Pacific/Guam", Label: "(GMT+10:00) Guam, Port Moresby"},
		{Value: "Asia/Vladivostok", Label: "(GMT+10:00) Vladivostok"},
		{Value: "Asia/Magadan", Label: "(GMT+11:00) Magadan, Solomon Is., New Caledonia"},
		{Value: "Pacific/Auckland", Label: "(GMT+12:00) Auckland, Wellington"},
		{Value: "Pacific/Fiji", Label: "(GMT+12:00) Fiji, Kamchatka, Marshall Is."},
		{Value: "Pacific/Tongatapu", Label: "(GMT+13:00) Nuku'alofa"},
	}
}
